#index:
#    path: /
#    controller: App\Controller\DefaultController::index
contact:
    path:       /{_locale}/News
    controller: App\Controller\NewsController::index
    requirements:
        _locale: en|fr|de